# Generated by Django 2.0.2 on 2018-02-10 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('paragraph_text', models.CharField(max_length=4095)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('parent_paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cites.Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('score', models.BigIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='paragraph',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cites.Story'),
        ),
    ]
