# Generated by Django 2.0.2 on 2018-02-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0002_auto_20180210_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paracite_profile.Profile'),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paracite_profile.Profile'),
        ),
    ]
