# Generated by Django 2.0.2 on 2018-02-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0004_auto_20180221_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='paragraph_text',
            new_name='text',
        ),
    ]
