# Generated by Django 2.0.2 on 2018-02-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cites', '0005_auto_20180221_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='url',
            field=models.CharField(default='ERROR', max_length=8),
            preserve_default=False,
        ),
    ]
