# Generated by Django 2.0.2 on 2018-02-23 10:42

from django.db import migrations

from cites.converters import id_to_url


def gen_url(apps, schema_editor):
    Story = apps.get_model('cites', 'Story')
    for row in Story.objects.all():
        row.url = id_to_url(row.id)
        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('cites', '0006_story_url'),
    ]

    operations = [
        migrations.RunPython(gen_url),
    ]
