# Generated by Django 2.0.2 on 2018-02-27 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paracite_profile', '0001_initial'),
        ('cites', '0007_populat_story_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(4, 'Very Good'), (3, 'Good'), (2, 'Neutral'), (1, 'Bad'), (0, 'Very Bad')])),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='rank',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='score',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='paracite_profile.Profile'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='votingrecord',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cites.Paragraph'),
        ),
        migrations.AddField(
            model_name='votingrecord',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paracite_profile.Profile'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='voters',
            field=models.ManyToManyField(related_name='voters', through='cites.VotingRecord', to='paracite_profile.Profile'),
        ),
    ]
