# Generated by Django 2.0.2 on 2018-04-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0010_auto_20180307_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='url',
        ),
        migrations.RemoveField(
            model_name='story',
            name='url',
        ),
    ]
