# Generated by Django 2.0.2 on 2018-04-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cites', '0011_auto_20180420_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='text',
            field=models.TextField(max_length=4095),
        ),
    ]
